_BASE_: "Base-CTW1500.yaml"
MODEL:
  WEIGHTS: "model_0470999.pth"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn" # "attn" "rnn"
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (8000,)
  MAX_ITER: 500000
  CHECKPOINT_PERIOD: 1000
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_NORM: 0.0
  GAMMA: 0.1
  BIAS_LR_FACTOR: 1.0
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "output/batext/ctw1500/attn_R_50"
