_BASE_: "Base-CTW1500.yaml"
MODEL:
  WEIGHTS: "output/batext/ctw1500/attn_R_50/model_final.pth"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn" # "attn" "rnn"
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0005
  STEPS: (8000,)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "output/batext/ctw1500/attn_R_50"
