_BASE_: "../Base-BAText.yaml"
MODEL:
  BATEXT:
    POOLER_RESOLUTION: (8,128)
    NUM_CHARS: 100
  FCOS:
    INFERENCE_TH_TEST: 0.6
DATASETS:
  TRAIN: ("ReCTS_train",)
  TEST: ("ReCTS_test",)
INPUT:
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1024
