_BASE_: "Base-Pretrain.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn" 
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  STEPS: (160000, 220000)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 20000
TEST:
  EVAL_PERIOD: 20000
OUTPUT_DIR: "output/batext/pretrain/attn_R_50"
